<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net9.0-windows10.0.19041.0</TargetFramework><UseWPF>true</UseWPF><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><AssemblyName>DuoMix</AssemblyName><RootNamespace>DuoMix</RootNamespace><Version>1.0.1</Version><Authors>Ixyrn</Authors><Company>Ixyrn</Company><Product>DuoMix</Product><Copyright>Copyright (c) 2026 Ixyrn</Copyright><DebugType>none</DebugType><DebugSymbols>false</DebugSymbols><Deterministic>true</Deterministic><PathMap>$(MSBuildProjectDirectory)=/src/DuoMix</PathMap><ApplicationIcon>Assets\DuoMix.ico</ApplicationIcon><StartupObject>DuoMix.Program</StartupObject></PropertyGroup>
<ItemGroup><PackageReference Include="NAudio" Version="3.1.0"/><Resource Include="Assets\DuoMix.png"/><Resource Include="Assets\Fonts\Rajdhani-Bold.ttf"/></ItemGroup>
</Project>


